# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCitationCFF: true
AddCodeOfConduct: false
AddCompatHelperCI: true
AddContributionDocs: false
AddCopierCI: false
AddDependabot: true
AddDocs: true
AddDocsCI: true
AddFormatterAndLinterConfigFiles: false
AddGitHubPRTemplate: false
AddGitHubTemplates: false
AddLintCI: false
AddLychee: false
AddMacToCI: true
AddTagBotCI: true
AddTestCI: true
AddWinToCI: true
Authors: yolhan <yolhan@laposte.net>
AutoIncludeTests: false
CheckExplicitImports: false
JuliaMinCIVersion: lts
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: yolhan
PackageName: RKDG
PackageOwner: yolhan83
PackageUUID: d48f45bf-26a3-5dd2-b875-a29975cd122b
RunJuliaNightlyOnCI: true
StrategyConfirmIncluded: true
StrategyLevel: 0
StrategyReviewExcluded: true
UseCirrusCI: false
_src_path: C:\Users\yolha\.julia\packages\BestieTemplate\jdG8v
