name = "RKDG"
uuid = "d48f45bf-26a3-5dd2-b875-a29975cd122b"
authors = ["yolhan <yolhan@laposte.net>"]
version = "0.1.0"

[deps]
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
Polynomials = "4.1.0"
julia = "1.10"
